name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Copy artifacts
        run: |
          rm -rf public
          mkdir -p public
          cp -r docs/.vitepress/dist/* public

      - name: Deploy to built branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout -b built
          git add .
          git commit -m "Automatic build and deploy from GitHub Actions"
          git push -f origin built
